#!/usr/bin/env bash
#
# install-proxy.sh — one-shot installer for a hardened 3proxy HTTP proxy.
#
# Meant to run ON the proxy machine (Ubuntu/Debian/RHEL/etc). It:
#   1. installs 3proxy (from apt if available, else builds from source)
#   2. writes a config with Basic auth on a chosen port
#   3. installs a systemd service (runs unprivileged, Restart=always)
#   4. locks the port to specific client IPs via iptables (+ persists them)
#   5. installs a 1-minute health-check watchdog (auto-restart if it hangs)
#   6. tests it and prints the credentials + how to add it to the scanner
#
# Usage (run as root, or a sudo-capable user):
#   sudo ./install-proxy.sh
#
# Configure via env vars (all optional):
#   PROXY_PORT=8899                       # listen port
#   PROXY_USER=scanner                    # basic-auth username
#   PROXY_PASS=<secret>                   # basic-auth password (default: random)
#   ALLOW_IPS="1.2.3.4,5.6.7.8"           # client IPs allowed through the firewall
#                                         # (empty = open to internet, auth-only — not recommended)
#   PROXY_VERSION=0.9.4                   # 3proxy source tag to build
#
# Examples:
#   sudo PROXY_PASS='mySecret' ALLOW_IPS='38.242.155.107,157.173.99.22' ./install-proxy.sh
#   sudo PROXY_PORT=8080 ./install-proxy.sh
#
set -euo pipefail

PROXY_PORT="${PROXY_PORT:-8899}"
PROXY_USER="${PROXY_USER:-scanner}"
PROXY_VERSION="${PROXY_VERSION:-0.9.4}"
ALLOW_IPS="${ALLOW_IPS:-}"

# ── pretty output ──
if [ -t 1 ]; then
  RED=$'\033[0;31m'; GRN=$'\033[0;32m'; YLW=$'\033[0;33m'; BLU=$'\033[0;34m'; BLD=$'\033[1m'; RST=$'\033[0m'
else RED=""; GRN=""; YLW=""; BLU=""; BLD=""; RST=""; fi
log()  { echo "${BLU}==>${RST} ${BLD}$*${RST}"; }
ok()   { echo "${GRN}  ✓${RST} $*"; }
warn() { echo "${YLW}  !${RST} $*"; }
die()  { echo "${RED}  ✗${RST} $*" >&2; exit 1; }

# ── sudo helper ──
SUDO=""
if [ "$(id -u)" -ne 0 ]; then
  command -v sudo >/dev/null 2>&1 || die "run as root or install sudo"
  SUDO="sudo"
fi

# ── package manager ──
if   command -v apt-get >/dev/null 2>&1; then PKG=apt
elif command -v dnf     >/dev/null 2>&1; then PKG=dnf
elif command -v yum     >/dev/null 2>&1; then PKG=yum
else PKG=""; fi
pkg_install() {
  case "$PKG" in
    apt) $SUDO env DEBIAN_FRONTEND=noninteractive apt-get update -y -qq \
         && $SUDO env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$@" ;;
    dnf) $SUDO dnf install -y -q "$@" ;;
    yum) $SUDO yum install -y -q "$@" ;;
    *)   warn "unknown package manager — install manually: $*" ;;
  esac
}

# ── password ──
gen_pass() { openssl rand -base64 18 2>/dev/null | tr -d '/+=' | cut -c1-22 || head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'; }
PROXY_PASS="${PROXY_PASS:-$(gen_pass)}"

echo "${BLD}${BLU}"
echo "  3proxy installer"
echo "  port : ${PROXY_PORT}"
echo "  user : ${PROXY_USER}"
echo "  allow: ${ALLOW_IPS:-<none — auth-only, open to internet>}"
echo "${RST}"

# ── 1. install 3proxy ──
if command -v 3proxy >/dev/null 2>&1 || [ -x /usr/local/bin/3proxy ]; then
  ok "3proxy already installed"
else
  log "Installing 3proxy"
  if [ "$PKG" = apt ] && apt-cache policy 3proxy 2>/dev/null | grep -q Candidate: && ! apt-cache policy 3proxy 2>/dev/null | grep -q 'Candidate: (none)'; then
    pkg_install 3proxy
    ok "3proxy installed from apt"
  else
    warn "3proxy not in package repo — building from source (${PROXY_VERSION})"
    pkg_install gcc make git ca-certificates
    tmp="$(mktemp -d)"
    git clone --depth 1 --branch "$PROXY_VERSION" https://github.com/3proxy/3proxy.git "$tmp/3proxy" >/dev/null 2>&1 \
      || die "git clone failed"
    ( cd "$tmp/3proxy" && ln -sf Makefile.Linux Makefile && make >/dev/null 2>&1 ) || die "build failed"
    [ -x "$tmp/3proxy/bin/3proxy" ] || die "build produced no binary"
    $SUDO install -m 0755 "$tmp/3proxy/bin/3proxy" /usr/local/bin/3proxy
    rm -rf "$tmp"
    ok "3proxy built + installed → /usr/local/bin/3proxy"
  fi
fi
BIN="$(command -v 3proxy || echo /usr/local/bin/3proxy)"

# ── 2. user + dirs + config ──
log "Configuring"
$SUDO id proxy3 >/dev/null 2>&1 || $SUDO useradd --system --no-create-home --shell /usr/sbin/nologin proxy3
$SUDO mkdir -p /etc/3proxy /var/log/3proxy
$SUDO chown proxy3:proxy3 /var/log/3proxy

$SUDO tee /etc/3proxy/3proxy.cfg >/dev/null <<EOF
# 3proxy — generated by install-proxy.sh
nserver 1.1.1.1
nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
maxconn 1000

# log to stdout -> systemd journal
log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h"

# basic authentication
users ${PROXY_USER}:CL:${PROXY_PASS}
auth strong
allow ${PROXY_USER}

# HTTP/HTTPS proxy
proxy -p${PROXY_PORT}
EOF
$SUDO chmod 0644 /etc/3proxy/3proxy.cfg
ok "config → /etc/3proxy/3proxy.cfg"

# ── 3. systemd service ──
$SUDO tee /etc/systemd/system/3proxy.service >/dev/null <<EOF
[Unit]
Description=3proxy (port ${PROXY_PORT})
After=network.target

[Service]
Type=simple
User=proxy3
Group=proxy3
ExecStart=${BIN} /etc/3proxy/3proxy.cfg
Restart=always
RestartSec=3
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
EOF
$SUDO systemctl daemon-reload
$SUDO systemctl enable --now 3proxy >/dev/null 2>&1
sleep 2
$SUDO systemctl is-active --quiet 3proxy && ok "service active (Restart=always)" || die "service failed — check: journalctl -u 3proxy"

# ── 4. firewall lockdown ──
if command -v iptables >/dev/null 2>&1; then
  log "Firewall (port ${PROXY_PORT})"
  if [ -n "$ALLOW_IPS" ]; then
    # clean prior rules for this port
    $SUDO iptables -D INPUT -p tcp --dport "$PROXY_PORT" -j DROP 2>/dev/null || true
    # DROP-all first so it ends up LAST after we insert ACCEPTs on top
    $SUDO iptables -A INPUT -p tcp --dport "$PROXY_PORT" -j DROP
    # always allow localhost
    $SUDO iptables -D INPUT -p tcp --dport "$PROXY_PORT" -s 127.0.0.1 -j ACCEPT 2>/dev/null || true
    $SUDO iptables -I INPUT 1 -p tcp --dport "$PROXY_PORT" -s 127.0.0.1 -j ACCEPT
    IFS=',' read -ra IPS <<< "$ALLOW_IPS"
    for ip in "${IPS[@]}"; do
      ip="$(echo "$ip" | tr -d ' ')"; [ -z "$ip" ] && continue
      $SUDO iptables -D INPUT -p tcp --dport "$PROXY_PORT" -s "$ip" -j ACCEPT 2>/dev/null || true
      $SUDO iptables -I INPUT 1 -p tcp --dport "$PROXY_PORT" -s "$ip" -j ACCEPT
    done
    ok "locked ${PROXY_PORT} to: ${ALLOW_IPS}, 127.0.0.1 (all else DROP)"
    # persist
    $SUDO mkdir -p /etc/iptables
    $SUDO bash -c "iptables-save > /etc/iptables/rules.v4"
    if [ "$PKG" = apt ]; then
      dpkg -l 2>/dev/null | grep -q iptables-persistent || \
        $SUDO env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq iptables-persistent >/dev/null 2>&1 || true
    fi
    ok "rules persisted → /etc/iptables/rules.v4"
  else
    warn "ALLOW_IPS not set — port ${PROXY_PORT} is OPEN to the internet (auth-only)."
    warn "Bots will hammer it. Strongly recommended: re-run with ALLOW_IPS=<your scanner IPs>."
  fi
else
  warn "iptables not found — skipping firewall lockdown (set ALLOW_IPS + install iptables)"
fi

# ── 5. self-healing watchdog ──
log "Health-check watchdog"
$SUDO tee /usr/local/bin/3proxy-healthcheck.sh >/dev/null <<EOF
#!/usr/bin/env bash
CODE=\$(timeout 8 curl -s -o /dev/null -w '%{http_code}' -x http://${PROXY_USER}:${PROXY_PASS}@127.0.0.1:${PROXY_PORT} http://example.com 2>/dev/null || echo 000)
if [ "\$CODE" != "200" ] && [ "\$CODE" != "407" ]; then
  logger -t 3proxy-healthcheck "3proxy unresponsive (code=\$CODE) — restarting"
  systemctl restart 3proxy
fi
EOF
$SUDO chmod +x /usr/local/bin/3proxy-healthcheck.sh
$SUDO tee /etc/systemd/system/3proxy-healthcheck.service >/dev/null <<EOF
[Unit]
Description=3proxy health check
After=3proxy.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/3proxy-healthcheck.sh
EOF
$SUDO tee /etc/systemd/system/3proxy-healthcheck.timer >/dev/null <<EOF
[Unit]
Description=Run 3proxy health check every minute

[Timer]
OnBootSec=2min
OnUnitActiveSec=1min

[Install]
WantedBy=timers.target
EOF
$SUDO systemctl daemon-reload
$SUDO systemctl enable --now 3proxy-healthcheck.timer >/dev/null 2>&1
ok "watchdog enabled (checks every minute)"

# ── 6. test ──
log "Testing"
command -v curl >/dev/null 2>&1 || pkg_install curl
NOAUTH=$(timeout 8 curl -s -o /dev/null -w '%{http_code}' -x "http://127.0.0.1:${PROXY_PORT}" http://example.com 2>/dev/null || echo 000)
AUTHOK=$(timeout 8 curl -s -o /dev/null -w '%{http_code}' -x "http://${PROXY_USER}:${PROXY_PASS}@127.0.0.1:${PROXY_PORT}" http://example.com 2>/dev/null || echo 000)
[ "$NOAUTH" = "407" ] && ok "no-auth rejected (407)" || warn "no-auth returned ${NOAUTH} (expected 407)"
[ "$AUTHOK" = "200" ] && ok "with-auth works (200)" || warn "with-auth returned ${AUTHOK} (expected 200)"

# public IPv4 for the connection string (force -4 so we don't print an IPv6)
PUBIP="$(timeout 6 curl -s4 http://ifconfig.me 2>/dev/null \
  || timeout 6 curl -s http://ip-api.com/line/?fields=query 2>/dev/null \
  || hostname -I | tr ' ' '\n' | grep -E '^[0-9]+\.' | head -1)"
[ -z "${PUBIP:-}" ] && PUBIP="<this-host-ip>"

echo
echo "${BLD}${GRN}3proxy is installed and running.${RST}"
echo
echo "  ${BLD}Proxy URL:${RST}   http://${PROXY_USER}:${PROXY_PASS}@${PUBIP}:${PROXY_PORT}"
echo "  ${BLD}Host:${RST}        ${PUBIP}"
echo "  ${BLD}Port:${RST}        ${PROXY_PORT}"
echo "  ${BLD}Username:${RST}    ${PROXY_USER}"
echo "  ${BLD}Password:${RST}    ${PROXY_PASS}"
echo
echo "  Add it in the scanner's ${BLD}Proxies${RST} page: scheme=http, host=${PUBIP}, port=${PROXY_PORT},"
echo "  username=${PROXY_USER}, password=<above>."
echo
echo "  Manage: ${BLD}systemctl status 3proxy${RST} | ${BLD}journalctl -u 3proxy -f${RST}"
[ -z "$ALLOW_IPS" ] && echo "  ${YLW}Reminder: lock it down — re-run with ALLOW_IPS=<scanner IPs>.${RST}"
